<a href="https://colab.research.google.com/github/ngtra14/Python/blob/main/Pandas_DataFrame_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creating DataFrame

In [1]:
import numpy as np
import pandas as pd

In [2]:
from pandas import Series, DataFrame
import numpy as np

In [3]:
series_obj=Series(np.arange(0,8,2),index=['row1','row2','row3','row4',])
series_obj

row1    0
row2    2
row3    4
row4    6
dtype: int64

In [4]:
series_obj.iloc[[0,1]]

row1    0
row2    2
dtype: int64

In [5]:
series_obj['row2']

2

In [6]:
df=DataFrame({'City':['Seattle','Chicago','NYC'], 'States':['WA','IL','NY'],'Avg':[100,200,500]})

In [7]:
df

City States  Avg
0  Seattle     WA  100
1  Chicago     IL  200
2      NYC     NY  500

Creating Series from a dictionary.

In [8]:
series_2=Series({'City':['Seattle','Chicago','NYC'], 'States':['WA','IL','NY'],'Avg':[100,200,500]})

In [9]:
series_2

City      [Seattle, Chicago, NYC]
States               [WA, IL, NY]
Avg               [100, 200, 500]
dtype: object

Converting a series directly into dataframe.
1. if no index specify, the dictionary key will become index. If we specify here and the index does not match the dictionary key, Naan value will appear.

In [10]:
no_index_df=DataFrame(series_2)
no_index_df

0
City    [Seattle, Chicago, NYC]
States             [WA, IL, NY]
Avg             [100, 200, 500]

In [11]:
not_matching_index=DataFrame(series_2,index=['City','A','B'])
not_matching_index

0
City  [Seattle, Chicago, NYC]
A                         NaN
B                         NaN

How do we change the index then?
1. If we change by .index() as below, the dictionary's key will be replaced by the new provied index list. The new index no longer needs to match the dictionary's key like when we transfrom earlier

In [12]:
dict_df=DataFrame(series_2,index=['City','States','Avg'])
dict_df.index=['Location','Demo','Income']
dict_df

0
Location  [Seattle, Chicago, NYC]
Demo                 [WA, IL, NY]
Income            [100, 200, 500]

2. If we want to keep the dictionary key, we need to reset the index then assign a new index. The new index can be anyvalue

In [13]:
key_and_new=DataFrame(series_2)
key_and_new
#before

0
City    [Seattle, Chicago, NYC]
States             [WA, IL, NY]
Avg             [100, 200, 500]

In [14]:
#after. makeing sure the inplace is set, otherwise it will replace, instead of adding another colum.
key_and_new.reset_index(inplace=True)
key_and_new

index                        0
0    City  [Seattle, Chicago, NYC]
1  States             [WA, IL, NY]
2     Avg          [100, 200, 500]

In [15]:
#change index
key_and_new.index=['Region','Upper region','Income']
key_and_new

index                        0
Region          City  [Seattle, Chicago, NYC]
Upper region  States             [WA, IL, NY]
Income           Avg          [100, 200, 500]

In [16]:
key_and_new.index

Index(['Region', 'Upper region', 'Income'], dtype='object')

Retrieving data from specific location

In [17]:
df=key_and_new.copy()
df
df.iloc[[1,2],[0]]

index
Upper region  States
Income           Avg

# Accessing elements & Modifying the dataframe

Slicing data from the dataframe

In [18]:
df.iloc[0:2,1]

Region          [Seattle, Chicago, NYC]
Upper region               [WA, IL, NY]
Name: 0, dtype: object

Accessing an entire column using indexing

In [19]:
df['age']=[30,45,60]
df


index                        0  age
Region          City  [Seattle, Chicago, NYC]   30
Upper region  States             [WA, IL, NY]   45
Income           Avg          [100, 200, 500]   60

In [20]:
df.iloc[:,[0,2]]

index  age
Region          City   30
Upper region  States   45
Income           Avg   60

Comparing- mask indexing
if not using the outer df[], it will return an object w/ boolean values contains the index position.
df[index statisfying the condition] >-- return actual value of the df

In [21]:
mask=df.iloc[:,2]>35
mask

Region          False
Upper region     True
Income           True
Name: age, dtype: bool

In [22]:
mask2=df[df.iloc[:,2]>35]
mask2

index                0  age
Upper region  States     [WA, IL, NY]   45
Income           Avg  [100, 200, 500]   60

Replacing value inside the dataframe

In [23]:
df

index                        0  age
Region          City  [Seattle, Chicago, NYC]   30
Upper region  States             [WA, IL, NY]   45
Income           Avg          [100, 200, 500]   60

replace the entire column value,column names vs. replace certain cell that satisfied a condition

In [24]:
df.iloc[:,1]=None
df

index     0  age
Region          City  None   30
Upper region  States  None   45
Income           Avg  None   60

In [25]:
df.columns=['Attribute','Values','Age',]
df

Attribute Values  Age
Region            City   None   30
Upper region    States   None   45
Income             Avg   None   60

If column Age is greater than 45 or smaller, then change the value in outcome accordingly.
1. accessing to filter the value of age <-- those are the rows that satisfy <-- df.iloc[:,2] because we are filtering along the row
2. using those defined rows, let's access the value in Column " Outcome" for those row and assign the new value. df.loc[filteredrow,'Outcome] <-- now accessing the value in the defined column.

In [26]:
df.iloc[:,2]=df.iloc[:,2].apply(lambda x:int(x))
df.loc[df.iloc[:,2]>45,'Outcome']=1
df.loc[df.iloc[:,2]<45,'Outcome']=0
df.loc[df.iloc[:,2]==45,'Outcome']=1000
df

Attribute Values  Age  Outcome
Region            City   None   30      0.0
Upper region    States   None   45   1000.0
Income             Avg   None   60      1.0

Modifying the dataframe to replace None value. Below code changing several lines with a list of value, making sure the [0:2] is the same length with the list

In [27]:
df.iloc[0:2,1]=[200,300]
df

Attribute Values  Age  Outcome
Region            City    200   30      0.0
Upper region    States    300   45   1000.0
Income             Avg   None   60      1.0

Now we are going to find all Null value <-- notice how we can find null value for the entire df or 1 specific columns.
Then replace w an average value

In [28]:
df['Values'].isnull()
df.isnull()

Attribute  Values    Age  Outcome
Region            False   False  False    False
Upper region      False   False  False    False
Income            False    True  False    False

In [29]:
df.fillna(250,inplace=True)
df
# making sure the inplace is specified, otherwise df will not commit the change

Attribute  Values  Age  Outcome
Region            City     200   30      0.0
Upper region    States     300   45   1000.0
Income             Avg     250   60      1.0

What if we want to fill multiple position with multiple values.

In [30]:
from pandas.core import missing
missing_df=df.copy()
missing_df['Homevalue']=None,None,None
missing_df['Numrooms']=20, None,None
missing_df

Attribute  Values  Age  Outcome Homevalue  Numrooms
Region            City     200   30      0.0      None      20.0
Upper region    States     300   45   1000.0      None       NaN
Income             Avg     250   60      1.0      None       NaN

The input for the fillna() - insde the bracket must be either scaler or a dictionary. If using dictionary then we need to match the column as the key, value is a nested dictionary with key=index(such as: region), value=value. Make sure you use inplace=True to commit the change. fillna() does not override existing data that is not Naan= region remains 20 instead of 1.  

In [31]:
missing_df.fillna({'Homevalue':100000,'Numrooms':{'Region':1 , 'Upper region':2,'Income':3}},inplace=True)
missing_df

Attribute  Values  Age  Outcome  Homevalue  Numrooms
Region            City     200   30      0.0     100000      20.0
Upper region    States     300   45   1000.0     100000       2.0
Income             Avg     250   60      1.0     100000       3.0

Let's try to see what if the nested dictionary isnt matching the index of the df <- the value remains None

In [32]:
second_missing=df.copy()
second_missing['Homevalue']=None,None,None
second_missing['Numrooms']=20, None,None
second_missing.fillna({'Homevalue':100000,'Numrooms':{'Region':1 , 'Home':2,'Income':3}},inplace=True)
second_missing

Attribute  Values  Age  Outcome  Homevalue  Numrooms
Region            City     200   30      0.0     100000      20.0
Upper region    States     300   45   1000.0     100000       NaN
Income             Avg     250   60      1.0     100000       3.0

we can also use fillna(method='ffill') <-- it will replace Naan with the last known value in the column.
Whatis about if we can to count for number of missing values? how much data is missing

In [33]:
count_missing=df.copy()
count_missing['Homevalue']=None,None,None
count_missing['Numrooms']=20, None,None
count_missing

Attribute  Values  Age  Outcome Homevalue  Numrooms
Region            City     200   30      0.0      None      20.0
Upper region    States     300   45   1000.0      None       NaN
Income             Avg     250   60      1.0      None       NaN

In [34]:
count_missing.isnull().sum()
# it returns the total missing values per columns.

Attribute    0
Values       0
Age          0
Outcome      0
Homevalue    3
Numrooms     2
dtype: int64

In [35]:
# can we count the total missing value per row then? remember if we want the function to follow direction of row in result, the axis=1
count_missing.isnull().sum(axis=1)


Region          1
Upper region    2
Income          2
dtype: int64

let's drop all the records with null values <- empty DF because everysingle row has an naan

In [36]:
count_missing.dropna(inplace=True)
count_missing

Empty DataFrame
Columns: [Attribute, Values, Age, Outcome, Homevalue, Numrooms]
Index: []

we also can dropna(axis=1) then it will drop all columns that contains None, keeping only the one that has no none.

How to find duplicate records and drop them ? Let's add new records first

In [37]:
df

Attribute  Values  Age  Outcome
Region            City     200   30      0.0
Upper region    States     300   45   1000.0
Income             Avg     250   60      1.0

1. appending a new duplicated data and ignoring the original index (ignore_index=True) <--  notice how the index change from 'region' to 0

In [38]:
new_record={'Attribute':'City','Values':200,'Age':30,'Outcome':0.0}
new_df=df.append(new_record,ignore_index=True)
new_df

<ipython-input-38-fa7171343291>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_df=df.append(new_record,ignore_index=True)


Attribute  Values  Age  Outcome
0      City     200   30      0.0
1    States     300   45   1000.0
2       Avg     250   60      1.0
3      City     200   30      0.0

2. How to add a new record to dataframe without losing the index <-- create the new record as a series with a given name

In [39]:
# @title
new_data =pd.Series({'Attribute':'City','Values':200,'Age':30,'Outcome':0.0},name='Region')
new_df_indexkeep=df.append(new_data,ignore_index=False)
new_df_indexkeep

<ipython-input-39-771dfcb7f7a0>:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_df_indexkeep=df.append(new_data,ignore_index=False)


Attribute  Values  Age  Outcome
Region            City     200   30      0.0
Upper region    States     300   45   1000.0
Income             Avg     250   60      1.0
Region            City     200   30      0.0

Now the data has duplicated records, let continue checking and removing them

In [40]:
new_df.duplicated()

0    False
1    False
2    False
3     True
dtype: bool

In [41]:
new_df_indexkeep.duplicated()

Region          False
Upper region    False
Income          False
Region           True
dtype: bool

The drop_duplicates allow to drop the entire row.

In [42]:
new_df.drop_duplicates(inplace=True)
new_df

Attribute  Values  Age  Outcome
0      City     200   30      0.0
1    States     300   45   1000.0
2       Avg     250   60      1.0

If we can to drop duplicates based on value of 1 specific column, we will need to pass on the name of that column. drop_duplicates(['nameofcol'])

In [43]:
new_df_indexkeep

Attribute  Values  Age  Outcome
Region            City     200   30      0.0
Upper region    States     300   45   1000.0
Income             Avg     250   60      1.0
Region            City     200   30      0.0

In [44]:
new_df_indexkeep.drop_duplicates(['Attribute'],inplace=True)
new_df_indexkeep

Attribute  Values  Age  Outcome
Region            City     200   30      0.0
Upper region    States     300   45   1000.0
Income             Avg     250   60      1.0

# Merging,Concatenate and transforming dataframes


Concate/Combine 2 dataframe by matching row-index value, meaning adding more columns

In [45]:
obj_1=pd.DataFrame(np.arange(36).reshape(6,6))
obj_1
# this is matrix size 6*6

0   1   2   3   4   5
0   0   1   2   3   4   5
1   6   7   8   9  10  11
2  12  13  14  15  16  17
3  18  19  20  21  22  23
4  24  25  26  27  28  29
5  30  31  32  33  34  35

In [46]:
obj_2=pd.DataFrame(np.arange(15).reshape(3,5))
obj_2
# this is matrix 3*5... reshape(row,col)

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14

# Concat 2 DF
Adding 2 DF using concat()

In [47]:
df=pd.concat([obj_1,obj_2],axis=1)
df
#axis=1 when we want to matching row index, increasing the number of col

0   1   2   3   4   5     0     1     2     3     4
0   0   1   2   3   4   5   0.0   1.0   2.0   3.0   4.0
1   6   7   8   9  10  11   5.0   6.0   7.0   8.0   9.0
2  12  13  14  15  16  17  10.0  11.0  12.0  13.0  14.0
3  18  19  20  21  22  23   NaN   NaN   NaN   NaN   NaN
4  24  25  26  27  28  29   NaN   NaN   NaN   NaN   NaN
5  30  31  32  33  34  35   NaN   NaN   NaN   NaN   NaN

In [48]:
df2=pd.concat([obj_1,obj_2],axis=0)
df2
## adding by matching col index, increasing the number of row

0   1   2   3   4     5
0   0   1   2   3   4   5.0
1   6   7   8   9  10  11.0
2  12  13  14  15  16  17.0
3  18  19  20  21  22  23.0
4  24  25  26  27  28  29.0
5  30  31  32  33  34  35.0
0   0   1   2   3   4   NaN
1   5   6   7   8   9   NaN
2  10  11  12  13  14   NaN

# Adding new record
Adding a new record into DF:
1. join <-- new col
2. append <-- new row

In [49]:
new_series=Series(np.arange(10),name='new_var')
new_series
# this series have 10 elements
new_added_df=DataFrame.join(df,new_series)
new_added_df
# this only join the series as a new column and matching the length

0   1   2   3   4   5     0     1     2     3     4  new_var
0   0   1   2   3   4   5   0.0   1.0   2.0   3.0   4.0        0
1   6   7   8   9  10  11   5.0   6.0   7.0   8.0   9.0        1
2  12  13  14  15  16  17  10.0  11.0  12.0  13.0  14.0        2
3  18  19  20  21  22  23   NaN   NaN   NaN   NaN   NaN        3
4  24  25  26  27  28  29   NaN   NaN   NaN   NaN   NaN        4
5  30  31  32  33  34  35   NaN   NaN   NaN   NaN   NaN        5

If we want to append a new row, the data must be sepcify by which value for which columns index. It different from adding a new column where you only need a name of series- which will be used as the col index.

In [50]:
#adding_row_df= df.append(new_series,ignore_index=False)
dfcopy=df.copy()
dfcopy.index=['a','b','c','d','e','g']
new_series_modified=Series({0:'A',1:'A',2:'A',3:'A',4:'A'})
new_series_modified
dfcopy.columns
dfcopy.append(new_series_modified,ignore_index=True)

<ipython-input-50-df7e4c5d3ca3>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dfcopy.append(new_series_modified,ignore_index=True)


0   1   2   3   4     5     0     1     2     3     4
0   0   1   2   3   4   5.0   0.0   1.0   2.0   3.0   4.0
1   6   7   8   9  10  11.0   5.0   6.0   7.0   8.0   9.0
2  12  13  14  15  16  17.0  10.0  11.0  12.0  13.0  14.0
3  18  19  20  21  22  23.0   NaN   NaN   NaN   NaN   NaN
4  24  25  26  27  28  29.0   NaN   NaN   NaN   NaN   NaN
5  30  31  32  33  34  35.0   NaN   NaN   NaN   NaN   NaN
6   A   A   A   A   A   NaN     A     A     A     A     A

# Melting

In [51]:
data=pd.DataFrame({'Name':['A','B','C','D','E'], 'Age':[10,20,30,40,50],'Edu':['HS','MS',"",'HS',""]})
data

Name  Age Edu
0    A   10  HS
1    B   20  MS
2    C   30    
3    D   40  HS
4    E   50

We are going to modify the abovedata with syntax learnt earlier.
1. break age into 3 group, under 25, between 25-50 and above <-- ***method using here is to create a new column, need to find how to replace directly in the "age" column without getting the error of comparing str vs. int***
2. remove na values and replace w/ previous values
3. concat this df with a new records
4. add a new income column and sort the data based on that colum


In [52]:
data_testing=data.copy()
data_testing.loc[data_testing['Age']<=25,'Group']='Under'
data_testing.loc[(data_testing['Age']<50) & (data_testing['Age']>25),'Group']='Middle'
data_testing.loc[data_testing['Age']>=50,'Group']='Senior'
data_testing

Name  Age Edu   Group
0    A   10  HS   Under
1    B   20  MS   Under
2    C   30      Middle
3    D   40  HS  Middle
4    E   50      Senior

In [53]:
data_testing.loc[data_testing['Edu']=="",'Edu']=None
data_testing.isna()

Name    Age    Edu  Group
0  False  False  False  False
1  False  False  False  False
2  False  False   True  False
3  False  False  False  False
4  False  False   True  False

In [54]:
#data_testing.dropna(axis=1)
data_testing.fillna(method='ffill',inplace=True)
data_testing

Name  Age Edu   Group
0    A   10  HS   Under
1    B   20  MS   Under
2    C   30  MS  Middle
3    D   40  HS  Middle
4    E   50  HS  Senior

In [55]:
data.loc[data['Edu']=="",'Edu']=None
data['Group']='Vary'
combine_axis_0=pd.concat([data,data_testing],axis=0)
combine_axis_0


Name  Age   Edu   Group
0    A   10    HS    Vary
1    B   20    MS    Vary
2    C   30  None    Vary
3    D   40    HS    Vary
4    E   50  None    Vary
0    A   10    HS   Under
1    B   20    MS   Under
2    C   30    MS  Middle
3    D   40    HS  Middle
4    E   50    HS  Senior

In [56]:
combine_axis_1=pd.concat([data,data_testing],axis=1)
combine_axis_1

Name  Age   Edu Group Name  Age Edu   Group
0    A   10    HS  Vary    A   10  HS   Under
1    B   20    MS  Vary    B   20  MS   Under
2    C   30  None  Vary    C   30  MS  Middle
3    D   40    HS  Vary    D   40  HS  Middle
4    E   50  None  Vary    E   50  HS  Senior

Notice how we have to sort by a unique column, thus combine_axis_0 can short by Age but not combine_axis_1

In [57]:
combine_axis_0.sort_values(by='Age',ascending=True,inplace=True)
combine_axis_0

Name  Age   Edu   Group
0    A   10    HS    Vary
0    A   10    HS   Under
1    B   20    MS    Vary
1    B   20    MS   Under
2    C   30  None    Vary
2    C   30    MS  Middle
3    D   40    HS    Vary
3    D   40    HS  Middle
4    E   50  None    Vary
4    E   50    HS  Senior

Pandas.melt() unpivots a DataFrame from wide format to long format.
melt() function is useful to massage a DataFrame into a format where one or more columns are identifier variables, while all other columns, considered measured variables, are unpivoted to the row axis, leaving just two non-identifier columns, variable and value.

pandas.melt(frame, id_vars=None, value_vars=None,
 var_name=None, value_name='value', col_level=None) ***bold text***

In [58]:
melt_df=pd.DataFrame({'Name': {0: 'John', 1: 'Bob', 2: 'Shiela'},
                   'Course': {0: 'Masters', 1: 'Graduate', 2: 'Graduate'},
                   'Age': {0: 27, 1: 23, 2: 21},
                      'ID':{0:1234,1:3456,2:5678}})
melt_df

Name    Course  Age    ID
0    John   Masters   27  1234
1     Bob  Graduate   23  3456
2  Shiela  Graduate   21  5678

In [59]:
pd.melt(melt_df,id_vars=['Name','ID'],value_vars=['Course'])

Name    ID variable     value
0    John  1234   Course   Masters
1     Bob  3456   Course  Graduate
2  Shiela  5678   Course  Graduate

In [60]:
pd.melt(melt_df,id_vars=['ID'],value_vars=['Course','Age','Name'],var_name='Attributes',value_name='Stat')

ID Attributes      Stat
0  1234     Course   Masters
1  3456     Course  Graduate
2  5678     Course  Graduate
3  1234        Age        27
4  3456        Age        23
5  5678        Age        21
6  1234       Name      John
7  3456       Name       Bob
8  5678       Name    Shiela

Another way of making wider dataframe into narrower is stack and unstack()

In [61]:
stack_df=melt_df.stack()
stack_df

0  Name          John
   Course     Masters
   Age             27
   ID            1234
1  Name           Bob
   Course    Graduate
   Age             23
   ID            3456
2  Name        Shiela
   Course    Graduate
   Age             21
   ID            5678
dtype: object

In [62]:
unstack_df=stack_df.unstack()
unstack_df

Name    Course Age    ID
0    John   Masters  27  1234
1     Bob  Graduate  23  3456
2  Shiela  Graduate  21  5678

***pandas.pivot(index, columns, values) ***function produces pivot table based on 3 columns of the DataFrame. Uses unique values from index / columns and fills with values.

Parameters:
index[ndarray] : Labels to use to make new frame’s index
columns[ndarray] : Labels to use to make new frame’s columns
values[ndarray] : Values to use for populating new frame’s values

Returns: Reshaped DataFrame
Exception: ValueError raised if there are any duplicates.

In [63]:
melt_df
new_records=Series({'Name':'Tracy','Course':'HS','Age':18,'ID':'1000'},name='3')
melt_df=melt_df.append(new_records,ignore_index=False)
melt_df

<ipython-input-63-374fac3e459f>:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  melt_df=melt_df.append(new_records,ignore_index=False)


Name    Course  Age    ID
0    John   Masters   27  1234
1     Bob  Graduate   23  3456
2  Shiela  Graduate   21  5678
3   Tracy        HS   18  1000

In [64]:
melt_df.pivot(index=['ID'],values=['Age','ID'],columns=['Course'])

Age                    ID              
Course Graduate   HS Masters Graduate    HS Masters
ID                                                 
1234        NaN  NaN      27      NaN   NaN    1234
3456         23  NaN     NaN     3456   NaN     NaN
5678         21  NaN     NaN     5678   NaN     NaN
1000        NaN   18     NaN      NaN  1000     NaN

So we pick a new row index: ID
columns[]: how many distinct values in this " Course" will be the new columns
values[]: based on the ID, the columns, which values to fill in the slot.

In [65]:
melt_df # modify melt_df to have a duplicated ID then perform pivot to see the missing index
melt_df=melt_df.append(Series({'Name':'John','Course':'HS','Age':19,'ID':'1234'},name='4'))
melt_df

<ipython-input-65-d79694b0cac1>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  melt_df=melt_df.append(Series({'Name':'John','Course':'HS','Age':19,'ID':'1234'},name='4'))


Name    Course  Age    ID
0    John   Masters   27  1234
1     Bob  Graduate   23  3456
2  Shiela  Graduate   21  5678
3   Tracy        HS   18  1000
4    John        HS   19  1234

Now let perform the pivot again with the duplicated value in the "ID" col, which will be used as index for the new table

In [66]:
dup_index_pivot=melt_df.pivot(index=['ID','Name'],columns=['Course'],values=['Age'])
# noticing how the ID for second John is missing

In [67]:
dup_index_pivot.reset_index()
# reset index release the missing ID since it is no longer the row index of the table

ID    Name      Age              
Course               Graduate    HS Masters
0       1234    John      NaN   NaN    27.0
1       3456     Bob     23.0   NaN     NaN
2       5678  Shiela     21.0   NaN     NaN
3       1000   Tracy      NaN  18.0     NaN
4       1234    John      NaN  19.0     NaN

# Numpy

In [68]:
# @title Creating multidimen array
import numpy as np

In [69]:
B= np.array([[0,1,2,3],[4,5,6,7],[2,3,4,5]])
print(B)

[[0 1 2 3]
 [4 5 6 7]
 [2 3 4 5]]


In [70]:
print(type(B))

<class 'numpy.ndarray'>


In [71]:
print(B.ndim) # number of dimension

2


In [72]:
print(B.shape) # number of col and row

(3, 4)


In [73]:
print(len(B)) # 1st number in the shape()

3


Let's create a more complex array


In [74]:
C1=np.array([[[1,2,3],[3,4,5]],[['a','b','c'],['d','e','f']]])
C2=np.array([[[10,20,30],[30,40,50]],[['aa','bb','cc'],['dd','ee','ff']]])
C3=np.array([C1,C2])
C4=np.array([C2,C1])
C5=np.array([C3,C4])
print(C5)

[[[[['1' '2' '3']
    ['3' '4' '5']]

   [['a' 'b' 'c']
    ['d' 'e' 'f']]]


  [[['10' '20' '30']
    ['30' '40' '50']]

   [['aa' 'bb' 'cc']
    ['dd' 'ee' 'ff']]]]



 [[[['10' '20' '30']
    ['30' '40' '50']]

   [['aa' 'bb' 'cc']
    ['dd' 'ee' 'ff']]]


  [[['1' '2' '3']
    ['3' '4' '5']]

   [['a' 'b' 'c']
    ['d' 'e' 'f']]]]]


In [75]:
print(C5.ndim)

5


In [76]:
print(C5.shape)  # counting the lens of the list from outer list into the inner list

(2, 2, 2, 2, 3)


In [77]:
print(len(C5))

2


There are multiple ways to creating a structured matrices as well. Below are few examples:

In [78]:
print(np.zeros((3,4))) # creating a matrice dim 3*4 with all Zeros values

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [79]:
test=np.ones((4,3,2))
print(test)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [80]:
print(test.ndim)
print(test.shape)

3
(4, 3, 2)


In [81]:
print(np.diag([1,2,3])) # creating diagnial , expecting a list of input <-- array contains the type of the list input

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [82]:
print(np.eye(3)) # creating identity matrix using float-ing point as the element type

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [83]:
A=np.empty((3,4)) # creating empty numpty array with set dimension/shapes, such as this one is 3*4 matrix. no value is assigned yet.
print(A)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [84]:
# @title Indexting & Slicing
print(C1)

[[['1' '2' '3']
  ['3' '4' '5']]

 [['a' 'b' 'c']
  ['d' 'e' 'f']]]


# Aggregations or reductions

In [93]:
print(np.max(test_array))
print(np.std(test_array))
print(np.mean(test_array))

9
2.581988897471611
5.0


Applying aggregated function along an axis:
axis=0 means column while axis=1 means row <> panda axis=1 col, axis=0 means row

In [97]:
print(B)
print(B.shape)
print(np.mean(B,axis=0))
print(np.mean(B,axis=1))

[[0 1 2 3]
 [4 5 6 7]
 [2 3 4 5]]
(3, 4)
[2. 3. 4. 5.]
[1.5 5.5 3.5]


# Universal Numpy Function
Apply a function to all element in an array in numpy needs 2 steps:
1. create the normal python function
2. turn that function into Numpy Universal function f_np

In [101]:
def f(x):
  from math import exp
  return exp(-(x**2))
f_np=np.frompyfunc(f,1,1)
print(f_np(B))

[[1.0 0.36787944117144233 0.01831563888873418 0.00012340980408667956]
 [1.1253517471925912e-07 1.3887943864964021e-11 2.3195228302435696e-16
  5.242885663363464e-22]
 [0.01831563888873418 0.00012340980408667956 1.1253517471925912e-07
  1.3887943864964021e-11]]
